### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by deearahman** [zerotypic/wasg-register#10]
python ./wasg-register.py -r 659xxxxxxx xxxxxxxxx
OTP will be sent to mobile phone number 65xxxxxxxx

Enter OTP to continue: 79----
Traceback (most recent call last):
  File "./wasg-register.py", line 383, in <module>
    sys.exit(main())
  File "./wasg-register.py", line 340, in main
    retrieve_mode=args.retrieve_mode)
  File "./wasg-register.py", line 188, in validate_otp
    "userid" : bytes(resp["body"]["userid"], "utf8"),
TypeError: str() takes at most 1 argument (2 given)

I got this error. Previously it worked for me. WirelessgX has an upgrade yesterday and now the script no longer working. Can you help.. Thanks!!

**Comment by zerotypic** [comment]
That should be because you're running it in Python 2. Try using Python 3 and it should hopefully work (I've not tested it yet). I could make some changes so it's backward compatible with Python 2, but since 2 is already deprecated it might not be worth it.

**Comment by tsehan** [comment]
```
python3 ./wasg-register.py -r 65xxxxxxxx DOB
OTP will be sent to mobile phone number 65xxxxxxxx
Enter OTP to continue: 89xxx
Traceback (most recent call last):
  File "./wasg-register.py", line 383, in <module>
    sys.exit(main())
  File "./wasg-register.py", line 340, in main
    retrieve_mode=args.retrieve_mode)
  File "./wasg-register.py", line 163, in validate_otp
    raise HTTPNotFoundExn("Failed to make validation query.")
__main__.HTTPNotFoundExn: Failed to make validation query.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./wasg-register.py", line 385, in <module>
    errprint("HTTP error: %s" % e.message)
AttributeError: 'HTTPNotFoundExn' object has no attribute 'message'
```

I am getting a nearly similar error.
Can't quite figure out what is the issue.

**Comment by zerotypic** [comment]
There was a bug in the error handling code, I've fixed it. I also made the exception report the status code, so you can see what the status code of the HTTP request was. The failed query was during validation, it could be because there was some update to the protocol. You could try using another ISP's server (default is Singtel, see if MyRepublic works). I don't really have time to work further on this now, so if there was a protocol update, this will be broken till somebody fixes the code.

**Comment by tsehan** [comment]
Thanks for the quick fix. As you mentioned there is still an error with the HTTP request.
I think you are right that there is an issue with the Singtel server. Haven't tried MyRepublic. The current ISPs from the Mac Wireless@SGx app are M1, Singtel, StarHub and TPG.
Managed a workaround to obtain the username and password from the Mac app for now. Tried to look but I can't find the ISP URLs to update the script.

**Comment by zerotypic** [comment]
You'll have to reverse engineer the official app to extract the URLs. Or somehow get IMDA (or GovTech or whoever is developing the app) to release them.

**Comment by jon-chuang** [comment]
Thx for keeping this updated, worked for me 1 year ago and updated script worked for me again today.

Unfortunately, wireless@sgx itself's a bitch.

**Comment by Michael-Jing** [comment]
> Thanks for the quick fix. As you mentioned there is still an error with the HTTP request. I think you are right that there is an issue with the Singtel server. Haven't tried MyRepublic. The current ISPs from the Mac Wireless@SGx app are M1, Singtel, StarHub and TPG. Managed a workaround to obtain the username and password from the Mac app for now. Tried to look but I can't find the ISP URLs to update the script.

May you share how to get he username and password from the Mac app?

**Comment by Michael-Jing** [comment]
> > Thanks for the quick fix. As you mentioned there is still an error with the HTTP request. I think you are right that there is an issue with the Singtel server. Haven't tried MyRepublic. The current ISPs from the Mac Wireless@SGx app are M1, Singtel, StarHub and TPG. Managed a workaround to obtain the username and password from the Mac app for now. Tried to look but I can't find the ISP URLs to update the script.
> 
> May you share how to get he username and password from the Mac app?

For anyone has the same question, it's to use the "keychain access" app.
